### ISSUE TITLE
CloudFormation should open up in a new tab, rather than where blogpost is.

### ISSUE THREAD

**Issue by sermolin** [aws-samples/amazon-sagemaker-w-snowflake-as-datasource#3]

**Comment by aarora79** [comment]
Right that is desirable but not possible from markdown due to several reasons including security reasons. See https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank. Closing this issue. When this blog post is put in an html page then this will open in a new tab so there it will be a non-issue, GitHub does not allow this.
